// Dummy data for the EdTech Admin Dashboard

export const dashboardStats = {
  totalStudents: 48291,
  activeTeachers: 1847,
  coursesPublished: 3642,
  aiUsageStats: 892341,
  dailyActiveUsers: 12847,
  revenue: 284750,
  quizAttempts: 94821,
  completionRate: 73.4,
};

export const revenueData = [
  { month: "Jan", revenue: 42000, subscriptions: 380, courses: 12000 },
  { month: "Feb", revenue: 58000, subscriptions: 420, courses: 15000 },
  { month: "Mar", revenue: 51000, subscriptions: 390, courses: 13500 },
  { month: "Apr", revenue: 67000, subscriptions: 510, courses: 18000 },
  { month: "May", revenue: 73000, subscriptions: 560, courses: 21000 },
  { month: "Jun", revenue: 89000, subscriptions: 640, courses: 25000 },
  { month: "Jul", revenue: 95000, subscriptions: 720, courses: 28000 },
  { month: "Aug", revenue: 112000, subscriptions: 810, courses: 32000 },
  { month: "Sep", revenue: 98000, subscriptions: 750, courses: 29000 },
  { month: "Oct", revenue: 124000, subscriptions: 890, courses: 36000 },
  { month: "Nov", revenue: 138000, subscriptions: 960, courses: 41000 },
  { month: "Dec", revenue: 156000, subscriptions: 1100, courses: 48000 },
];

export const aiUsageData = [
  { day: "Mon", notes: 1240, quizzes: 890, summaries: 650, podcasts: 320 },
  { day: "Tue", notes: 1580, quizzes: 1120, summaries: 780, podcasts: 410 },
  { day: "Wed", notes: 1320, quizzes: 960, summaries: 590, podcasts: 280 },
  { day: "Thu", notes: 1890, quizzes: 1340, summaries: 920, podcasts: 520 },
  { day: "Fri", notes: 2100, quizzes: 1560, summaries: 1080, podcasts: 640 },
  { day: "Sat", notes: 1650, quizzes: 1200, summaries: 840, podcasts: 480 },
  { day: "Sun", notes: 980, quizzes: 720, summaries: 490, podcasts: 210 },
];

export const courseDistribution = [
  { name: "Technology", value: 35, color: "#6366f1" },
  { name: "Business", value: 22, color: "#a855f7" },
  { name: "Design", value: 18, color: "#06b6d4" },
  { name: "Science", value: 12, color: "#22c55e" },
  { name: "Arts", value: 8, color: "#f59e0b" },
  { name: "Others", value: 5, color: "#ef4444" },
];

export const engagementData = [
  { time: "00:00", users: 420 },
  { time: "02:00", users: 280 },
  { time: "04:00", users: 180 },
  { time: "06:00", users: 520 },
  { time: "08:00", users: 1840 },
  { time: "10:00", users: 3200 },
  { time: "12:00", users: 4100 },
  { time: "14:00", users: 3800 },
  { time: "16:00", users: 4500 },
  { time: "18:00", users: 5200 },
  { time: "20:00", users: 4800 },
  { time: "22:00", users: 2900 },
];

export const students = [
  {
    id: "STU001",
    name: "Arjun Sharma",
    email: "arjun.sharma@email.com",
    avatar: null,
    course: "Full Stack Development",
    progress: 78,
    status: "active",
    subscription: "Pro",
    joinDate: "2024-01-15",
    lastActive: "2024-12-10",
    quizScore: 88,
    country: "India",
    aiUsage: 342,
  },
  {
    id: "STU002",
    name: "Priya Patel",
    email: "priya.patel@email.com",
    avatar: null,
    course: "Data Science & ML",
    progress: 92,
    status: "active",
    subscription: "Enterprise",
    joinDate: "2023-11-20",
    lastActive: "2024-12-11",
    quizScore: 95,
    country: "India",
    aiUsage: 521,
  },
  {
    id: "STU003",
    name: "Marcus Johnson",
    email: "marcus.j@email.com",
    avatar: null,
    course: "UI/UX Design",
    progress: 45,
    status: "inactive",
    subscription: "Basic",
    joinDate: "2024-03-08",
    lastActive: "2024-11-28",
    quizScore: 72,
    country: "USA",
    aiUsage: 128,
  },
  {
    id: "STU004",
    name: "Sofia Rodriguez",
    email: "sofia.r@email.com",
    avatar: null,
    course: "Digital Marketing",
    progress: 63,
    status: "active",
    subscription: "Pro",
    joinDate: "2024-02-14",
    lastActive: "2024-12-09",
    quizScore: 81,
    country: "Spain",
    aiUsage: 267,
  },
  {
    id: "STU005",
    name: "Yuki Tanaka",
    email: "yuki.t@email.com",
    avatar: null,
    course: "Machine Learning",
    progress: 87,
    status: "active",
    subscription: "Enterprise",
    joinDate: "2023-09-01",
    lastActive: "2024-12-11",
    quizScore: 93,
    country: "Japan",
    aiUsage: 489,
  },
  {
    id: "STU006",
    name: "Ahmed Hassan",
    email: "ahmed.h@email.com",
    avatar: null,
    course: "Cybersecurity",
    progress: 34,
    status: "suspended",
    subscription: "Basic",
    joinDate: "2024-05-22",
    lastActive: "2024-10-15",
    quizScore: 58,
    country: "Egypt",
    aiUsage: 89,
  },
  {
    id: "STU007",
    name: "Emma Wilson",
    email: "emma.w@email.com",
    avatar: null,
    course: "Python Programming",
    progress: 71,
    status: "active",
    subscription: "Pro",
    joinDate: "2024-01-30",
    lastActive: "2024-12-10",
    quizScore: 84,
    country: "UK",
    aiUsage: 312,
  },
  {
    id: "STU008",
    name: "Raj Kumar",
    email: "raj.kumar@email.com",
    avatar: null,
    course: "Cloud Computing",
    progress: 56,
    status: "active",
    subscription: "Pro",
    joinDate: "2024-04-11",
    lastActive: "2024-12-08",
    quizScore: 76,
    country: "India",
    aiUsage: 198,
  },
];

export const teachers = [
  {
    id: "TCH001",
    name: "Dr. Sarah Mitchell",
    email: "sarah.mitchell@edtech.com",
    avatar: null,
    specialization: "Machine Learning & AI",
    courses: 12,
    students: 4821,
    rating: 4.9,
    status: "verified",
    earnings: 48200,
    joinDate: "2022-06-15",
    aiContentGenerated: 1240,
    country: "USA",
  },
  {
    id: "TCH002",
    name: "Prof. Rahul Gupta",
    email: "rahul.gupta@edtech.com",
    avatar: null,
    specialization: "Full Stack Development",
    courses: 8,
    students: 3642,
    rating: 4.8,
    status: "verified",
    earnings: 36800,
    joinDate: "2022-09-20",
    aiContentGenerated: 892,
    country: "India",
  },
  {
    id: "TCH003",
    name: "Lisa Chen",
    email: "lisa.chen@edtech.com",
    avatar: null,
    specialization: "UI/UX Design",
    courses: 6,
    students: 2180,
    rating: 4.7,
    status: "pending",
    earnings: 22400,
    joinDate: "2023-02-10",
    aiContentGenerated: 567,
    country: "China",
  },
  {
    id: "TCH004",
    name: "James O'Brien",
    email: "james.obrien@edtech.com",
    avatar: null,
    specialization: "Cybersecurity",
    courses: 5,
    students: 1890,
    rating: 4.6,
    status: "verified",
    earnings: 19600,
    joinDate: "2023-05-18",
    aiContentGenerated: 423,
    country: "Ireland",
  },
  {
    id: "TCH005",
    name: "Aisha Patel",
    email: "aisha.patel@edtech.com",
    avatar: null,
    specialization: "Data Science",
    courses: 9,
    students: 3210,
    rating: 4.9,
    status: "verified",
    earnings: 41500,
    joinDate: "2022-11-30",
    aiContentGenerated: 1089,
    country: "India",
  },
];

export const courses = [
  {
    id: "CRS001",
    title: "Complete Machine Learning Bootcamp",
    instructor: "Dr. Sarah Mitchell",
    category: "Technology",
    students: 4821,
    rating: 4.9,
    price: 89,
    status: "published",
    thumbnail: null,
    duration: "42 hours",
    lessons: 186,
    aiSummary: true,
    createdAt: "2023-08-15",
    revenue: 42900,
    completionRate: 68,
  },
  {
    id: "CRS002",
    title: "Full Stack Web Development 2024",
    instructor: "Prof. Rahul Gupta",
    category: "Technology",
    students: 3642,
    rating: 4.8,
    price: 79,
    status: "published",
    thumbnail: null,
    duration: "56 hours",
    lessons: 248,
    aiSummary: true,
    createdAt: "2023-06-20",
    revenue: 28800,
    completionRate: 72,
  },
  {
    id: "CRS003",
    title: "UI/UX Design Masterclass",
    instructor: "Lisa Chen",
    category: "Design",
    students: 2180,
    rating: 4.7,
    price: 69,
    status: "review",
    thumbnail: null,
    duration: "28 hours",
    lessons: 124,
    aiSummary: false,
    createdAt: "2024-01-10",
    revenue: 15000,
    completionRate: 81,
  },
  {
    id: "CRS004",
    title: "Advanced Cybersecurity & Ethical Hacking",
    instructor: "James O'Brien",
    category: "Technology",
    students: 1890,
    rating: 4.6,
    price: 99,
    status: "published",
    thumbnail: null,
    duration: "38 hours",
    lessons: 162,
    aiSummary: true,
    createdAt: "2023-10-05",
    revenue: 18700,
    completionRate: 59,
  },
  {
    id: "CRS005",
    title: "Data Science with Python & R",
    instructor: "Aisha Patel",
    category: "Technology",
    students: 3210,
    rating: 4.9,
    price: 84,
    status: "published",
    thumbnail: null,
    duration: "48 hours",
    lessons: 210,
    aiSummary: true,
    createdAt: "2023-07-22",
    revenue: 26900,
    completionRate: 75,
  },
  {
    id: "CRS006",
    title: "Digital Marketing & SEO 2024",
    instructor: "Emma Wilson",
    category: "Business",
    students: 1560,
    rating: 4.5,
    price: 59,
    status: "draft",
    thumbnail: null,
    duration: "22 hours",
    lessons: 98,
    aiSummary: false,
    createdAt: "2024-03-15",
    revenue: 9200,
    completionRate: 88,
  },
];

export const podcasts = [
  {
    id: "POD001",
    title: "The Future of AI in Education",
    course: "Machine Learning Bootcamp",
    duration: "28:45",
    plays: 12840,
    voice: "Neural Voice Pro",
    status: "published",
    createdAt: "2024-11-20",
    transcript: true,
  },
  {
    id: "POD002",
    title: "React 19 - What's New?",
    course: "Full Stack Development",
    duration: "22:18",
    plays: 8920,
    voice: "Studio Voice",
    status: "published",
    createdAt: "2024-11-28",
    transcript: true,
  },
  {
    id: "POD003",
    title: "Design Thinking Fundamentals",
    course: "UI/UX Design Masterclass",
    duration: "35:12",
    plays: 5640,
    voice: "Natural Voice",
    status: "processing",
    createdAt: "2024-12-01",
    transcript: false,
  },
  {
    id: "POD004",
    title: "Zero Trust Security Architecture",
    course: "Cybersecurity",
    duration: "41:30",
    plays: 4280,
    voice: "Neural Voice Pro",
    status: "published",
    createdAt: "2024-11-15",
    transcript: true,
  },
];

export const quizzes = [
  {
    id: "QZ001",
    title: "Python Fundamentals Assessment",
    course: "Full Stack Development",
    questions: 25,
    attempts: 3842,
    avgScore: 74,
    difficulty: "medium",
    status: "active",
    aiGenerated: true,
    createdAt: "2024-10-15",
    passRate: 68,
  },
  {
    id: "QZ002",
    title: "Machine Learning Algorithms Quiz",
    course: "ML Bootcamp",
    questions: 40,
    attempts: 2910,
    avgScore: 68,
    difficulty: "hard",
    status: "active",
    aiGenerated: true,
    createdAt: "2024-10-22",
    passRate: 54,
  },
  {
    id: "QZ003",
    title: "UI Design Principles Test",
    course: "UI/UX Design",
    questions: 20,
    attempts: 1840,
    avgScore: 82,
    difficulty: "easy",
    status: "active",
    aiGenerated: false,
    createdAt: "2024-11-05",
    passRate: 89,
  },
  {
    id: "QZ004",
    title: "Network Security Fundamentals",
    course: "Cybersecurity",
    questions: 35,
    attempts: 1290,
    avgScore: 71,
    difficulty: "hard",
    status: "draft",
    aiGenerated: true,
    createdAt: "2024-11-18",
    passRate: 62,
  },
];

export const transactions = [
  {
    id: "TXN001",
    student: "Arjun Sharma",
    course: "Full Stack Development",
    amount: 79,
    plan: "Pro Monthly",
    status: "completed",
    date: "2024-12-10",
    method: "Razorpay",
    invoice: "INV-2024-001",
  },
  {
    id: "TXN002",
    student: "Priya Patel",
    course: "ML Bootcamp",
    amount: 299,
    plan: "Enterprise Annual",
    status: "completed",
    date: "2024-12-09",
    method: "Stripe",
    invoice: "INV-2024-002",
  },
  {
    id: "TXN003",
    student: "Marcus Johnson",
    course: "UI/UX Design",
    amount: 69,
    plan: "Basic Monthly",
    status: "pending",
    date: "2024-12-08",
    method: "PayPal",
    invoice: "INV-2024-003",
  },
  {
    id: "TXN004",
    student: "Sofia Rodriguez",
    course: "Digital Marketing",
    amount: 59,
    plan: "Pro Monthly",
    status: "completed",
    date: "2024-12-07",
    method: "Razorpay",
    invoice: "INV-2024-004",
  },
  {
    id: "TXN005",
    student: "Yuki Tanaka",
    course: "Data Science",
    amount: 299,
    plan: "Enterprise Annual",
    status: "refunded",
    date: "2024-12-06",
    method: "Stripe",
    invoice: "INV-2024-005",
  },
];

export const notifications = [
  {
    id: "NOT001",
    type: "ai",
    title: "AI Content Generation Complete",
    message: "Study notes for 'React Hooks' have been generated successfully.",
    time: "2 min ago",
    read: false,
    priority: "normal",
  },
  {
    id: "NOT002",
    type: "student",
    title: "New Student Registration",
    message: "Arjun Sharma has enrolled in Full Stack Development course.",
    time: "15 min ago",
    read: false,
    priority: "normal",
  },
  {
    id: "NOT003",
    type: "payment",
    title: "Payment Received",
    message: "₹5,999 received from Priya Patel for Enterprise plan.",
    time: "1 hour ago",
    read: true,
    priority: "high",
  },
  {
    id: "NOT004",
    type: "alert",
    title: "System Alert",
    message: "AI token usage at 85% of monthly limit. Consider upgrading.",
    time: "3 hours ago",
    read: false,
    priority: "high",
  },
  {
    id: "NOT005",
    type: "teacher",
    title: "Teacher Approval Request",
    message: "Lisa Chen has submitted a new course for review.",
    time: "5 hours ago",
    read: true,
    priority: "normal",
  },
];

export const recentActivities = [
  { id: 1, user: "Arjun Sharma", action: "completed", target: "React Hooks Module", time: "2 min ago", type: "completion" },
  { id: 2, user: "AI System", action: "generated", target: "50 quiz questions for ML course", time: "8 min ago", type: "ai" },
  { id: 3, user: "Priya Patel", action: "scored 95%", target: "Python Assessment", time: "15 min ago", type: "quiz" },
  { id: 4, user: "Dr. Sarah Mitchell", action: "published", target: "New lecture: Neural Networks", time: "32 min ago", type: "publish" },
  { id: 5, user: "Marcus Johnson", action: "enrolled in", target: "UI/UX Design Masterclass", time: "1 hour ago", type: "enrollment" },
  { id: 6, user: "AI System", action: "generated podcast", target: "Future of AI in Education", time: "2 hours ago", type: "ai" },
  { id: 7, user: "Sofia Rodriguez", action: "submitted", target: "Digital Marketing Assignment", time: "3 hours ago", type: "submission" },
  { id: 8, user: "Admin", action: "approved", target: "James O'Brien teacher application", time: "4 hours ago", type: "approval" },
];

export const aiModels = [
  { id: "openai", name: "OpenAI GPT-4o", status: "active", usage: 68, tokens: 2840000, cost: 142 },
  { id: "gemini", name: "Google Gemini Pro", status: "active", usage: 22, tokens: 920000, cost: 46 },
  { id: "ollama", name: "Ollama Llama 3.2", status: "active", usage: 8, tokens: 340000, cost: 0 },
  { id: "huggingface", name: "HuggingFace Mistral", status: "inactive", usage: 2, tokens: 80000, cost: 4 },
];

export const subscriptionPlans = [
  {
    id: "basic",
    name: "Basic",
    price: 9.99,
    students: 18420,
    features: ["5 courses", "Basic AI tools", "Email support"],
    color: "from-gray-500 to-gray-600",
    revenue: 183900,
  },
  {
    id: "pro",
    name: "Pro",
    price: 29.99,
    students: 24180,
    features: ["Unlimited courses", "Full AI suite", "Priority support", "Certificates"],
    color: "from-indigo-500 to-purple-600",
    revenue: 725000,
    popular: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 99.99,
    students: 5691,
    features: ["Everything in Pro", "Custom AI models", "Dedicated support", "Analytics API"],
    color: "from-purple-600 to-cyan-500",
    revenue: 568900,
  },
];

export const leaderboard = [
  { rank: 1, name: "Priya Patel", score: 9840, courses: 8, streak: 42, badge: "🏆" },
  { rank: 2, name: "Yuki Tanaka", score: 9210, courses: 7, streak: 38, badge: "🥈" },
  { rank: 3, name: "Arjun Sharma", score: 8750, courses: 6, streak: 31, badge: "🥉" },
  { rank: 4, name: "Emma Wilson", score: 8120, courses: 5, streak: 28, badge: "⭐" },
  { rank: 5, name: "Raj Kumar", score: 7890, courses: 6, streak: 24, badge: "⭐" },
  { rank: 6, name: "Sofia Rodriguez", score: 7540, courses: 4, streak: 19, badge: "⭐" },
  { rank: 7, name: "Marcus Johnson", score: 6920, courses: 3, streak: 15, badge: "⭐" },
  { rank: 8, name: "Ahmed Hassan", score: 5840, courses: 2, streak: 8, badge: "⭐" },
];
